### ISSUE TITLE
incorrect y axis label

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/ggformula#146] opened 2021-03-03 14:46 UTC
Any idea why the y axis label is inheriting the Y value label from the linear model?

``` r
suppressPackageStartupMessages(library(mosaic))
mod1 <- lm(pcs ~ mcs, data = HELPrct) %>%
  broom::augment()
gf_point(.resid ~ mcs, data = mod1) %>%
  gf_smooth() %>%
  gf_lm()
#> `geom_smooth()` using method = 'loess'
```

![](https://i.imgur.com/8h4kguo.png)

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by rpruim** [comment] 2021-06-21 15:02
Just noticing this.  Sorry for the delay.

The issue is with {broom}, which labels the residuals that way:

``` r
suppressPackageStartupMessages(library("mosaicData"))
suppressPackageStartupMessages(library("ggformula"))
mod1 <- lm(pcs ~ mcs, data = HELPrct) %>%
  broom::augment()

attributes(mod1$.resid)
#> $label
#> [1] "SF-36 Physical Component Score"
```

<sup>Created on 2021-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We could avoid this if we changed the way we look for labels.  Currently, we use the label attribute if it exists.  We could be pickier and require that the variable have one of several specified classes (like "labelled" or "declared").

Reconsidering labels is on the to-do list -- see #148

**Comment by rpruim** [comment] 2021-06-21 16:05
I'm going to close this in favor of #148.  I've also posted an issue to {broom} to see if the current behavior is desired.  See https://github.com/tidymodels/broom/issues/1031

**Closed by rpruim** 2021-06-21 16:05 UTC
